name: Start Notion backup

on:
  push:
    branches: [ master ]

  workflow_dispatch: # per avvio manuale

  # ogni 2 giorni alle 04:05 UTC
  schedule:
    - cron: '5 4 2-30/2 * *'

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11

    - name: Build with Maven
      run: mvn -B package --file pom.xml --no-transfer-progress

    # Nuovo step: crea il file JSON da usare
    - name: Create Google Service Account JSON file
      run: |
        echo "${{ secrets.GOOGLE_DRIVE_SERVICE_ACCOUNT_SECRET_JSON }}" > service_account.json
        
- name: Wait before starting backup
  run: sleep 180  # aspetta 60 secondi per lasciare il tempo a Notion di preparare l'export

    - name: Start Notion Backup
      run: java -jar ./target/notion-backup-1.0-SNAPSHOT.jar
      env:
        NOTION_SPACE_ID: ${{ secrets.NOTION_SPACE_ID }}
        NOTION_TOKEN_V2: ${{ secrets.NOTION_TOKEN_V2 }}

        GOOGLE_DRIVE_ROOT_FOLDER_ID: ${{ secrets.GOOGLE_DRIVE_ROOT_FOLDER_ID }}
        GOOGLE_DRIVE_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_DRIVE_SERVICE_ACCOUNT }}
        GOOGLE_DRIVE_SERVICE_ACCOUNT_SECRET_JSON: ${{ secrets.GOOGLE_DRIVE_SERVICE_ACCOUNT_SECRET_JSON }}
        GOOGLE_DRIVE_SERVICE_ACCOUNT_SECRET_FILE_PATH: service_account.json
        
        DROPBOX_ACCESS_TOKEN: ${{ secrets.DROPBOX_ACCESS_TOKEN }}
        DROPBOX_APP_KEY: ${{ secrets.DROPBOX_APP_KEY }}
        DROPBOX_APP_SECRET: ${{ secrets.DROPBOX_APP_SECRET }}
        DROPBOX_REFRESH_TOKEN: ${{ secrets.DROPBOX_REFRESH_TOKEN }}

        NEXTCLOUD_EMAIL: ${{ secrets.NEXTCLOUD_EMAIL }}
        NEXTCLOUD_PASSWORD: ${{ secrets.NEXTCLOUD_PASSWORD }}
        NEXTCLOUD_WEBDAV_URL: ${{ secrets.NEXTCLOUD_WEBDAV_URL }}

        PCLOUD_ACCESS_TOKEN: ${{ secrets.PCLOUD_ACCESS_TOKEN }}
        PCLOUD_API_HOST: ${{ secrets.PCLOUD_API_HOST }}
        PCLOUD_FOLDER_ID: ${{ secrets.PCLOUD_FOLDER_ID }}

        DOWNLOADS_DIRECTORY_PATH: /tmp/
